### ISSUE TITLE
Does not support orientation changes

### ISSUE THREAD

**Issue by slorber** [expo/status-bar-height#10]
Hi,

This component does not support well device orientation changes.

As far as I understand the code, it only listen for willChange events, and does nothing for didChange

Let's consider that I have an app in portrait mode first.
It's an iphone XS (actually a simulator)

When I rotate it to landscape I get

![image](https://user-images.githubusercontent.com/749374/52584750-2f1ab500-2e33-11e9-8e2a-df19671e83d5.png)

So the user callback will be fired with 0, which seems fine to me

But once the device is rotated back to portrait, the height for both events will actually be 0:

![image](https://user-images.githubusercontent.com/749374/52584923-aea88400-2e33-11e9-9864-05468b757167.png)

One workaroud that seems to work in my app is to do this, but obviously there is a little bit of flickering due to async nature of the workaround:

```js
    const handler = async height => {
      setStatusBarHeight(height)
      const realHeight = await StatusBarHeight.getAsync();
      setStatusBarHeight(realHeight);
    };
    StatusBarHeight.addEventListener(handler);
    return () => StatusBarHeight.removeEventListener(handler);
```

Maybe this kind of workaround can be included in the lib until something better/synchronous is possible (maybe Fabric will help?)

**Comment by EvanBacon** [comment]
This package has been deprecated in favor of [react-native-safe-area-context](https://github.com/th3rdwave/react-native-safe-area-context/) which supports orientation changes.
