### ISSUE TITLE
Constants.statusBarHeight is not updated

### ISSUE THREAD

**Issue by lc3t35** [expo/status-bar-height#2]
If you have an incoming call first (before launching the app) and then you launch the app, it is started with Constants.statusBarHeight = 40
If you use it in StyleSheet a paddingTop: Constants.statusBarHeight,
when you close the call, this constant is not updated, leaving a gray zone and moving the app 20 pixels down.
Using EStyleSheet I found this workaround :
````
paddingTop: Constants.statusBarHeight > 20 ? Constants.statusBarHeight - 20 : Constants.statusBarHeight,
````

**Comment by EvanBacon** [comment]
This package has been deprecated in favor of [react-native-safe-area-context](https://github.com/th3rdwave/react-native-safe-area-context/) which updates reactively.
