### ISSUE TITLE
Android error: StatusBarManager.getHeight is not a function

### ISSUE THREAD

**Issue by giladgray** [expo/status-bar-height#20]
I am running this on my Android phone and receiving an error that seems like it shouldn't happen:
```
[Unhandled promise rejection: TypeError: StatusBarManager.getHeight is not a function. (In 'StatusBarManager.getHeight(function (_ref) {]
at /Users/giladgray/peregrine/peregrine-frontend-3/node_modules/@expo/status-bar-height/lib/index.js:35:6 in Promise$argument_0
at /Users/giladgray/peregrine/peregrine-frontend-3/node_modules/@expo/status-bar-height/lib/index.js:34:4 in StatusBarHeight#getAsync
```

looking at the source code, `SBM.getHeight` seems specifically for iOS and should be undefined on Android, but it isn't.
perhaps the check needs to be beefier, like `typeof SBM.gH === 'function'` or `'getHeight' in SBM` to ensure that it really exists before attempting to call it.

**Comment by EvanBacon** [comment]
This package has been deprecated in favor of [react-native-safe-area-context](https://github.com/th3rdwave/react-native-safe-area-context/) which is a more cross platform.
