### ISSUE TITLE
Listen to StatusBar component hidden prop

### ISSUE THREAD

**Issue by Waltari10** [expo/status-bar-height#3]
When I change the StatusBar status using the React-Native component StatusBar, the events are not triggered. Any way of achieving this? Cmd + y works fine on the simulator though!

```
import { StatusBar } from 'react-native'

<StatusBar
    hidden={false}
/>
```

**Comment by EvanBacon** [comment]
This package has been deprecated in favor of [react-native-safe-area-context](https://github.com/th3rdwave/react-native-safe-area-context/) which should fix this issue.
