### ISSUE TITLE
Integration with react-navigation / SafeAreaView ?

### ISSUE THREAD

**Issue by slorber** [expo/status-bar-height#6]
Hi,

This library is helpful to listen for ios statusbar changes. However, it's not really clear to me how this is supposed to integrate with ReactNavigation or SafeAreaView, which most of us are probably using.

What would you recommend for such an integration?

**Comment by slorber** [comment]
As far as I understand I can write the following integration:

```js
export const trackStatusBarHeightChanges = async () => {
  const initialHeight = await StatusBarHeight.getAsync();
  SafeAreaView.setStatusBarHeight(initialHeight);
  const listener = height => SafeAreaView.setStatusBarHeight(height);
  StatusBarHeight.addEventListener(listener);
  return () => StatusBarHeight.removeEventListener(listener);
};
```

Unfortunately `setStatusBarHeight` does not trigger a re-render, I've made a [PR](https://github.com/react-community/react-native-safe-area-view/pull/38)

**Comment by slorber** [comment]
Unfortunately this integration does not seem to work fine, when the in-call statusbar is visible there's an additional unwanted offset:

![](https://i.imgur.com/NapqMhw.png)

**Comment by slorber** [comment]
This weird hack seems to fix it:

```js
const setStatusBarHeight = height => {
  console.debug('setStatusBarHeight', height);
  if (Platform.OS === 'ios' && height === 40) {
    SafeAreaView.setStatusBarHeight(20);
  } else {
    SafeAreaView.setStatusBarHeight(height);
  }
};
```

**Comment by EvanBacon** [comment]
This package has been deprecated in favor of [react-native-safe-area-context](https://github.com/th3rdwave/react-native-safe-area-context/) which we've already integrated with react-navigation!
