### ISSUE TITLE
Transform ES6+ to ES5 for Jest runner

### ISSUE THREAD

**Issue by usrbowe** [expo/status-bar-height#7]
## Issue
Currently when I use this package and run Jest test suite, it will throw error on unexpected token for `import`. 

## Solution
Transform all ES6+, like: `import` to `require` before publishing to `npm`.

## Error log
```js
import { NativeEventEmitter, NativeModules } from 'react-native';
^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
      at Object.<anonymous> (utilities/XXXXX.js:1:202)
      at Object.<anonymous> (screens/XXXXX.js:26:21)
```

## Temporary solution
Add 
```
transformIgnorePatterns: [ 'node_modules/@expo/status-bar-height' ],
```
to `jest/config.js`

**Comment by EvanBacon** [comment]
This package has been deprecated in favor of [react-native-safe-area-context](https://github.com/th3rdwave/react-native-safe-area-context/) which should be easier to mock for jest.
