### ISSUE TITLE
Doesn't work at Android. TypeError: undefined is not an object (evaluating '_this.emitter.addListener')

### ISSUE THREAD

**Issue by flalex** [expo/status-bar-height#8]
Checked locally and at snack:
https://snack.expo.io/@bacon/status-bar-height-example

![image](https://user-images.githubusercontent.com/818999/45537975-d0ff8c80-b816-11e8-97a7-348e1cc50662.png)

**Comment by EvanBacon** [comment]
This package has been deprecated in favor of [react-native-safe-area-context](https://github.com/th3rdwave/react-native-safe-area-context/) which fixes this issue.
